# NumPy

NumPy is a library that is written in C programming language. Since C is a statically-typed programming language, it is much more faster than dynamically-typed languages like Python.

## Basics

In [1]:
import numpy as np

In [2]:
# Arrays: faster way to handle data in Python
array01 = np.array([1, 5, 9, 3, 5, 7]) # to create an array
# arrays are type-sensitive so all elements should have same type

array02 = np.array([range(i, i + 3) for i in [2, 4, 6]])
# we can create multi-dimensional arrays
print(array02)
print()

# Create a length-10 integer array filled with zeros
array03 = np.zeros(10, dtype=int) # dtype: to define type of elements in an array
print(array03)
print()

# Create a 3x5 floating-point array filled with ones
array04 = np.ones((3, 5), dtype=float)
print(array04)

# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

[[2 3 4]
 [4 5 6]
 [6 7 8]]

[0 0 0 0 0 0 0 0 0 0]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[2, 0, 5],
       [7, 3, 6],
       [5, 2, 2]])

## Array Attributes

In [3]:
# Creating a three-dimensional array
x1 = np.random.randint(10, size=(3, 4, 5))
# size=(number of dimension, size of dimension's rows, size of dimension's columns)
print(x1)
print("--------------------------------------------------------")
# Each array has attributes ndim (the number of dimensions), shape (the size of each dimension) and size (total)
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size) # 3*4*5

# Another useful attribute is the dtype, the data type of the array
print("x1 dtype:", x1.dtype)
print("--------------------------------------------------------")
# Other attributes include itemsize, which lists the size (in bytes) of each array element
# and nbytes, which lists the total size (in bytes) of the array


# Array Indexing

# Values can be modified using any of the index notation
print(x1[0, 0])
x1[0, 0, 0] = 5
print(x1[0, 0])
print("--------------------------------------------------------")

# Array Slicing

# x[start:stop:step] If any of these are unspecified
# they default to the values start=0, stop=size of dimension, step=1

x2 = np.arange(10)
x2_sub = x2[1::2] # x2_sub is a subarray of x2. Since it is not a copy, changings in subarray affects main array
x2_sub_copy = x2_sub.copy() # to create a copy of an array
print(x2)
print(x2_sub)
print("--------------------------------------------------------")

# Reshaping of Arrays

grid = np.arange(1, 10).reshape((3, 3))
print(grid)
print("--------------------------------------------------------")

# Array Concatenation and Splitting

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.concatenate([x, y]).reshape((2, 3)) # Concatenates two arrays
print(z)
print()

x[0] = 9
# vertically stack the arrays
print(np.vstack([x, z]))
print()

y = np.array([[99],
              [99]])
print(np.hstack([z, y]))
print("--------------------------------------------------------")

# Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)
print("--------------------------------------------------------")


# Computation on NumPy

# np.absolute() or np.abs()
# np.sin(), cos, tan
# np.power(3, x)
# np.log(x)


# Aggregations on NumPy

# np.sum()
# np.max(), np.min()


# Broadcasting (Yaymak)

x = np.arange(3)
y = np.arange(3)[:, np.newaxis]
print(x, end="\n")
print(y, end="\n")
print(x+y)
print("--------------------------------------------------------")


# Boolean Arrays

#np.all(), np.any() give boolean expression

# Masking
x = np.arange(10)
masked = x[x>5] # gives an array filled with all the values that meet the condition
print(masked)

[[[2 7 8 9 3]
  [1 2 4 2 8]
  [8 1 8 5 0]
  [8 0 8 3 8]]

 [[2 6 1 6 2]
  [1 8 1 3 0]
  [9 4 9 4 9]
  [4 4 4 2 2]]

 [[1 4 6 5 6]
  [5 6 6 3 3]
  [9 2 2 0 9]
  [4 8 7 8 3]]]
--------------------------------------------------------
x1 ndim:  3
x1 shape: (3, 4, 5)
x1 size:  60
x1 dtype: int32
--------------------------------------------------------
[2 7 8 9 3]
[5 7 8 9 3]
--------------------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
--------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------------
[[1 2 3]
 [3 2 1]]

[[9 2 3]
 [1 2 3]
 [3 2 1]]

[[ 1  2  3 99]
 [ 3  2  1 99]]
--------------------------------------------------------
[1 2 3] [99 99] [3 2 1]
--------------------------------------------------------
[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
--------------------------------------------------------
[6 7 8 9]


## Indice and Sorting

In [4]:
x = np.arange(2, 7)
np.random.shuffle(x)
print(x)
i = np.argsort(x) # gives indices of sorted array
print(i)

[4 2 3 5 6]
[1 2 0 3 4]


In [5]:
rand = np.random.RandomState(42) # ?
z = rand.randint(5, 35, (4, 4)) # random.randint(low, high=None, size=None, dtype=int)
print(z)
print()

print(np.sort(z, axis=0))
print()

print(np.sort(z, axis=1))

[[11 24 33 19]
 [15 12 33 25]
 [11 30 23 27]
 [15 15 28 25]]

[[11 12 23 19]
 [11 15 28 25]
 [15 24 33 25]
 [15 30 33 27]]

[[11 19 24 33]
 [12 15 25 33]
 [11 23 27 30]
 [15 15 25 28]]


In [6]:
x = np.array([5, 8, 7, 6, 8, 2, 1, 3, 0])
print(np.partition(x, 4)) # returns an array which is sorted wrt the key value. left of array is smaller than key

[2 0 3 1 5 8 6 7 8]


In [7]:
#%% Structured Data

# Imagine that we have several categories of data on a number of people
# To save this data on a single structure, we use structured datas
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

# We can create a structured array using a compound data type specification
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)
print()

data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [8]:

#%% How to get the minimum and maximum value of a given NumPy array along the second axis?
data = [[10, 10, 90, 90],
        [40, 40, 60, 60],
        [55, 55, 65, 65],
        [10, 30, 60, 90]]
a1 = np.array(data)
amax = np.amax(a1, 0) # First axis means column-wise and second axis means row-wise.
# For amax, by default: axis=0 means second axis(row-wise)
amax2 = np.max(a1, 0) # We can also use max function with axis attribute instead of amax function.
# For max, by default: axis=0 means first axis(column-wise)
amin = np.amin(a1, 1)
amin2 = np.min(a1, axis=1)

print(amax)
print(amax2)
print(amin)
print(amin2)

[55 55 90 90]
[55 55 90 90]
[10 40 55 10]
[10 40 55 10]
